language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ngedemer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ngedemer/docker-react npm run test
